Create .github/workflow directory
koomekevo/hello-microverse pull request #1
Opened 2021-10-19 10:12 UTC by koomekevo

2021-10-19 11:48 UTC, carlos-ssh requested changes
Hi @koomekevo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![changesrequested](https://user-images.githubusercontent.com/22258274/137903213-65e698d6-b97a-46bd-875d-1186a9f27e3d.gif)




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-19 11:48 UTC, carlos-ssh commented on hello-microverse.html
> +<!DOCTYPE html>
- Provide a description in your Pull Request about the features implemented.

2021-10-19 11:48 UTC, carlos-ssh commented on README.md
> +# hello-microverse
- Provide a README fully described you can use the [template](https://github.com/microverseinc/readme-template) provided by Microverse.

2021-10-19 11:48 UTC, carlos-ssh commented on README.md
> +CSS
- Add in your ``.gitignore`` file your ``test.md`` file and ``node_modules`` directory.

2021-10-20 07:22 UTC, Mihndim2020 requested changes
## Hi @koomekevo , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)


 # Status: Requires Changes ♻️
_Check the comments below under the review._

Please do consider, as requested by the previews reviewer:
- [ ] Pull Request should have a short summary describing introduced changes in more details i.e what you have done in this particular milestone(eg; created an index.html, created style.css file etc).

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 07:22 UTC, Mihndim2020 commented on README.md
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
- [ ] This should be steps on how to clone this project locally(on your local machine) and how to run it. Please kindly fix it.

2021-10-20 07:22 UTC, Mihndim2020 commented on README.md
> +/in/linked
- [ ] Please kindly remove this as it make your readme dirty. Visitors are potential recruiters need to see that you page attention to details.

2021-10-20 07:22 UTC, Mihndim2020 commented on README.md
> +
- [ ] Kindly update you readme file with the information in the image below. See [template]([url](https://github.com/microverseinc/readme-template))
![koom](https://user-images.githubusercontent.com/65852621/138045881-67bae050-2f52-4526-aa95-c221648d39e1.png)

2021-10-20 10:06 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Kevin Mbae, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-20 10:42 UTC, merged